from . import db
class Investor(Form):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100))
    forename = db.Column(db.String(100))
    surname = db.Column(db.String(100))
    company = db.Column(db.String(100))
    phone = db.Column(db.String(100))
    gender = db.Column(db.String(20))
    category = db.Column(db.String(200))
    budget = db.Column(db.Integer)
    startuplocation = db.Column(db.String(100))
    numberofpeople = db.Column(db.Integer)
    stage = db.Column(db.String(50))
    returntype = db.Column(db.String(200))  

class Startup(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100))
    full_name = db.Column(db.String(100))
    name = db.Column(db.String(100))
    location = db.Column(db.String(100))
    category = db.Column(db.String(100))
    description = db.Column(db.String(200))
    phone_number = db.Column(db.String(20))
    gender = db.Column(db.String(10))
    budget_need = db.Column(db.Integer)
    company_location = db.Column(db.String(100))
    return_type_startup = db.Column(db.String(100))
    additional_support = db.Column(db.String(100))